### ISSUE TITLE
Allow for editing values

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikestart#21]
Right now, the "review my entry" screen just lets you see the values you entered—but if you go back to one of the earlier steps, you can't see the data you already entered—the fields are all blank.

This can be a bit confusing and makes the review screen a bit pointless, since you can't really "change" things per se.

Let's show the entered values in the input fields instead, which should make things much easier to use.

**Comment by danielwrobert** [comment]
There are a couple of ways I think we can handle this. One if the localStorage approach I'd mentioned earlier. The other (just thinking off of the top of my head) is to just set the value of the component equal to the state for that value from within the function that handles the change (once it's fired off).

**Comment by sarahmonster** [comment]
I was thinking the latter would be simpler & more straightforward to implement—I think it's just a matter of passing the state over to the input component.

I was looking at this for the pattern: https://facebook.github.io/react/docs/forms.html

**Comment by danielwrobert** [comment]
Correct. And I agree. The localStorage approach would be a little nicer because we can store the values and save them if the user returns or accidentally refreshes the page. But I don't think that's critical, just a nice enhancement that we _could_ consider later. The latter, as you mentioned, would be the approach we should start with. I'll add that in - I assigned myself this ticket the other day.

**Comment by sarahmonster** [comment]
Closed via #31
