### ISSUE TITLE
Navigation needs indicator of current step

### ISSUE THREAD

**Issue by sarahmonster** [a8cteam51/strikestart#5]
Right now, it's super confusing flipping between screens because step 1 is always indicated! Ideally, the currently-active step will be indicated (CSS class) and completed steps as well (CSS class would do).

It should look more like this:
![progress-bar](https://user-images.githubusercontent.com/376315/27589403-32de89a6-5b43-11e7-814c-d9b751c1e8c1.png)

Showing the currently-active step will probably be a little bit easier. I might be able to make this happen with CSS, but I think it's going to be less hacky to do via JS. Something like this https://stackoverflow.com/questions/38436351/react-add-class-active-on-selected-tab or this https://github.com/reactjs/react-router-tutorial/tree/master/lessons/05-active-links might do the trick.

I might be able to figure this one out (especially if the latter method works!), so I'm going to take a stab at it today.

For the completed steps, I'm thinking we'll need to add a state for each step, then once all portions of that step have been completed, we can change its state to "completed" .... and ... reflect that in the component? I'll need to go back to looking at how state works to figure this one out.

**Comment by danielwrobert** [comment]
The approach to take is the second link you posted above, since we're already using React Router. 

I actually already have this resolved locally but I hadn't pushed anything yet. Reason being is that I was having an issue with the `IndexRoute`. I actually needed to change that to `IndexRedirect`. But in React Router versions _below_ v3, it the component was just `Redirect`. Apparently, it changed to `IndexRedirect` in v3 but I didn't realize that because I don't often use it. Then in v4 it's changed to `Switch`, it seems. Which we're on v3 for this project, at the moment so I haven't dug into that yet.

Anyhow, I can push this up in a PR for you to review!
